### ISSUE TITLE
useSearch hook throws error when Yoast is not activated. 

### ISSUE THREAD

**Issue by burhandodhy** [10up/headstartwp#565]
### Describe the bug

If Yoast is not activated, using the useSearch hook throws an error. The behavior remains the same whether I remove YoastSEO from the integrations in `headless.config.js` or set it to `false`.

```
 error Error: Error serializing `.fallback["#url:\"/wp-json/wp/v2/posts\",args:#sourceUrl:\"https://headstart.test\",search:\"test\",postType:\"post\",_embed:true,,"].queriedObject.search.yoast_head` returned from `getServerSideProps` in "/search/[[...path]]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:52:19)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:59:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:56:39)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:59:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:56:39)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:59:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:56:39)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:59:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:56:39)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:59:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:56:39)
    at isSerializableProps (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/lib/is-serializable-props.js:79:12)
    at renderToHTMLImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/server/render.js:637:86)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/server/base-server.js:1058:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/server/base-server.js:1218:28)
    at async /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/server/response-cache/index.js:99:36 {
  digest: undefined
}
```

### Steps to Reproduce

1. Setup environment by following the quick steps https://headstartwp.10up.com/docs/learn/getting-started/quick-setup/
2. Go to `/search/` page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Interesting - I'm pretty sure this was reported in the past but I couldn't reproduce it anymore at that time. I'll take another look at this.

On another note, we're looking to revamp the `useSearch` hook here #547 which would likely change how we're handling SEO for search pages.

**Comment by dustinrue** [comment]
Just a note that I am able to reproduce this error on a default install of WP site with default content present running twenty twenty three theme.
