### ISSUE TITLE
Server Error - TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by burhandodhy** [10up/headstartwp#569]
### Describe the bug

Whenever I try to add the Image or Gallery block to the post, it ends with an error.

Block Markup 
```
<!-- wp:image {"id":22324,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="https://headtstartwp.test/wp-content/uploads/2023/07/image-853x1024.png" alt="" class="wp-image-22324"/></figure>
<!-- /wp:image -->
```

### Steps to Reproduce

1. Create a Post
2. Add Image Or Gallery block

### Screenshots, screen recording, code snippet

```
TypeError: Cannot read properties of undefined (reading 'length')
    at __spreadArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockTypography.js:3:66)
    at useBlockTypography (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockTypography.js:37:24)
    at useBlockAttributes (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockAttributes.js:28:66)
    at ImageBlock (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/ImageBlock.js:22:71)
    at renderWithHooks (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
- error Error [TypeError]: Cannot read properties of undefined (reading 'length')
    at __spreadArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockTypography.js:3:66)
    at useBlockTypography (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockTypography.js:37:24)
    at useBlockAttributes (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/hooks/useBlockAttributes.js:28:66)
    at ImageBlock (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/@headstartwp/core/dist/cjs/react/blocks/ImageBlock.js:22:71)
    at renderWithHooks (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderForwardRef (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5859:5)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7) {
  digest: undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicholasio** [comment]
Could you try with the `next` tag for both packages? 

[1.1.0-next.0](https://github.com/10up/headstartwp/releases/tag/%40headstartwp%2Fcore%401.1.0-next.0)

**Comment by burhandodhy** [comment]
@nicholasio  I updated both packages, and now I'm getting a different error.

```
error Error: Image with src "https://headstartwp.test/wp-content/uploads/2022/01/image-300%C3%97360px.png" has invalid "width" property. Expected a numeric value in pixels but received "NaN".
    at getImgProps (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/shared/lib/get-img-props.js:270:27)
    at /Users/burhannasir/wp-local-docker-sites/headstart/node_modules/next/dist/client/image-component.js:275:84
    at renderWithHooks (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/burhannasir/wp-local-docker-sites/headstart/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7) {
  digest: undefined
```

**Comment by nicholasio** [comment]
@burhandodhy can you tell me which theme you have active? And do you have a custom theme.json?
